build:
  environment:
    php: 7.4

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    coverage:
      services:
        rabbitmq: 3

      tests:
        override:
          - command: XDEBUG_MODE=coverage composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover

filter:
  excluded_paths:
    - 'tests/*'
