build:
  environment:
    php: 7.4
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    static_analysis:
      # Install gearman manually because "pecl_extensions" is executed before this node
      dependencies:
        before:
          - sudo apt-get install -y libgearman-dev
          - pecl install gearman

      environment:
        docker:
          remote_engine: true
        php:
          pecl_extensions:
            - redis
#      services:
#        rabbitmq: 3

      tests:
        override:
          - command: XDEBUG_MODE=coverage composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover

filter:
  excluded_paths:
    - 'tests/*'
