build:
  environment:
    php: 7.4

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    static_analysis:
      environment:
        docker: true
        php:
          pecl_extensions:
            - rdkafka
            - gearman
#      services:
#        rabbitmq: 3

      tests:
        override:
          - command: XDEBUG_MODE=coverage composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover
          - command: composer require --ignore-platform-req=ext-rdkafka "kwn/php-rdkafka-stubs:~1.1.0"
          - command: composer run psalm
          - command: docker run --rm -v `pwd`:/app nyholm/roave-bc-check || true # Ignore BC break errors

filter:
  excluded_paths:
    - 'tests/*'
