language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

addons:
  apt:
    packages:
      - rabbitmq-server

services:
  - rabbitmq

install:
  - travis_retry composer install

script:
  - composer tests
